sudo: required

language: bash

services:
  - docker

before_install:
- sudo docker run -v $(pwd):/my-snap snapcore/snapcraft sh -c "apt update && cd /my-snap && snapcraft schemacrawler"
- ls -la
- sudo apt-get install snapd
- sudo snap try --devmode prime
- snap list schemacrawler
- sudo schemacrawler -help
- which schemacrawler 
