name: schemacrawler
version: 15.01.04

# More details about what is contained in the snap.
summary: Schemacrawler ...
description: Schemacrawler ...

# License for the snap content, based on SPDX license expressions.


# Type of snap, defaults to "app".
type: app

# List of architectures the snap may run on. Defaults to [all].
architectures:
    - all
# List of applications (commands, binaries, daemons) in the snap. 
apps:
  schemacrawler:
      # Path to executable (relative to snap base) and arguments to use
      # when this application is run.
      command: schemacrawler-15.01.04-distribution/_schemacrawler/schemacrawler.sh
      environment: 
          JAVA_HOME: $SNAP/usr/lib/jvm/java-1.8.0-openjdk-$SNAP_ARCH
          PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
      
parts:
    schemacrawler:
        source:  https://github.com/schemacrawler/SchemaCrawler/releases/download/v15.01.04/schemacrawler-15.01.04-distribution.zip
        #source-checksum:  sha512/84897ee88677630102ed004f2f9df76fb0d7880dc9621d8a3679ec11ffdc0a2bc3a2ffdf1adb2591b7bd6c6acc4ae7efcecd92d3acf6bdeed4ab770b1d89f6f7
        plugin: dump
        build-packages:
            - openjdk-8-jre-headless
        stage-packages:
            - openjdk-8-jdk
